print("Basic Calculator")
num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")
Addition = float(num1) + float(num2)
Subtraction = float(num1) - float(num2)
Multiplication = float(num1) * float(num2)
Division = float(num1) / float(num2)
print("The sum of the numbers is = " + str(Addition))
print("The difference of the numbers is = " + str(Subtraction))
print("The product of the numbers is = " + str(Multiplication))
print("The qoutient of the numbers is =" + str(Division))

# here if we use int() we get whole numbers , to use decimals we have to use float()
